filter_tuple = open("../classbench-ng/filter_tuple_trace", "r")
port = set()
x = filter_tuple.readlines()
for i in x:
    i = i.strip().split("\t")
    port.add(i[2])
    port.add(i[3])
print(len(port))
print(sorted([int(i) for i in port]))
filter_tuple.close()